[package]
name = "spin-http-trigger"
authors = ["Rajat Jindal <rajatjindal83@gmail.com>"]
description = ""
version = "0.18.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
spin-sdk = "2.2.0"

[workspace]
