[package]
name = "spin-redis-trigger"
version = "0.15.1"
authors = ["Suneet Nangia <suneetnangia@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
bytes = "1"
# Do not change spin sdk version without testing the e2e.
spin-sdk = "2.2.0"

[workspace]