name: build
on:
  workflow_call:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
              os: "ubuntu-latest",
              arch: "x86_64",
            }
          - {
              os: "ubuntu-latest",
              arch: "aarch64"
            }
    env:
      ARCH: ${{ matrix.config.arch }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        env:
          RUST_CACHE_KEY_OS: rust-cache-${{ matrix.config.os }}-{{ matrix.config.arch}}
      - name: Setup build env
        run: |
          make setup
      - name: Build spin shim
        run: |
          VERBOSE=1 make build
      - name: Run unit tests spin shim
        run: |
          VERBOSE=1 make unit-tests
      - name: Lowercase the runner OS name
        shell: bash
        run: |
          OS=$(echo "${{ runner.os }}" | tr '[:upper:]' '[:lower:]')
          echo "RUNNER_OS=$OS" >> $GITHUB_ENV
      - name: Package release assets
        run: |
          mkdir _dist
          cp target/${{ matrix.config.arch }}-unknown-linux-musl/release/containerd-shim-spin-v2 _dist/
          cd _dist
          tar czf containerd-shim-spin-v2-${{ env.RUNNER_OS }}-${{ matrix.config.arch }}.tar.gz containerd-shim-spin-v2
      - name: Upload shim artifacts
        uses: actions/upload-artifact@v4
        with:
          name: containerd-shim-spin-v2-${{ env.RUNNER_OS }}-${{ matrix.config.arch }}
          path: _dist/containerd-shim-spin-v2-${{ env.RUNNER_OS }}-${{ matrix.config.arch }}.tar.gz
          retention-days: 5
